FROM python 3.7

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8



ARG AIRFLOW_VERSION=1.10.10
ARG AIRFLOW_USER_HOME=/usr/local/airflow
ARG AIRFLOW_DEPS=""
ARG PYTHON_DEPS=""
ENV AIRFLOW_HOME=${AIRFLOW_USER_HOME}


COPY ./requirements-python3.7.txt /requirements-python3.7.txt

RUN set -ex \ 
	&& apt-get update \
	&& 


